# Diccionario que contiene la efectividad de cada tipo de Pokémon contra otros tipos.
# Este diccionario se usa para calcular la efectividad de un ataque de un Pokémon contra otro Pokémon.
# En caso de no estar el tipo de ataque en el diccionario, se asume que la efectividad es 1.0 (efectividad normal).

effectiveness: dict[str, dict[str, float]] = {
    "Normal": {
        "Roca": 0.5,
        "Acero": 0.5,
        "Fantasma": 0.0,
    },
    "Fuego": {
        "Planta": 2.0,
        "Hielo": 2.0,
        "Bicho": 2.0,
        "Acero": 2.0,
        "Fuego": 0.5,
        "Agua": 0.5,
        "Roca": 0.5,
        "Dragón": 0.5,
    },
    "Agua": {
        "Fuego": 2.0,
        "Tierra": 2.0,
        "Roca": 2.0,
        "Agua": 0.5,
        "Planta": 0.5,
        "Dragón": 0.5,
    },
    "Planta": {
        "Agua": 2.0,
        "Tierra": 2.0,
        "Roca": 2.0,
        "Fuego": 0.5,
        "Planta": 0.5,
        "Veneno": 0.5,
        "Volador": 0.5,
        "Bicho": 0.5,
        "Dragón": 0.5,
        "Acero": 0.5,
    },
    "Eléctrico": {
        "Agua": 2.0,
        "Volador": 2.0,
        "Planta": 0.5,
        "Eléctrico": 0.5,
        "Dragón": 0.5,
        "Tierra": 0.0,
    },
    "Hielo": {
        "Planta": 2.0,
        "Tierra": 2.0,
        "Volador": 2.0,
        "Dragón": 2.0,
        "Fuego": 0.5,
        "Agua": 0.5,
        "Hielo": 0.5,
        "Acero": 0.5,
    },
    "Lucha": {
        "Normal": 2.0,
        "Hielo": 2.0,
        "Roca": 2.0,
        "Siniestro": 2.0,
        "Acero": 2.0,
        "Veneno": 0.5,
        "Volador": 0.5,
        "Psíquico": 0.5,
        "Bicho": 0.5,
        "Hada": 0.5,
        "Fantasma": 0.0,
    },
    "Veneno": {
        "Planta": 2.0,
        "Hada": 2.0,
        "Veneno": 0.5,
        "Tierra": 0.5,
        "Roca": 0.5,
        "Fantasma": 0.5,
        "Acero": 0.0,
    },
    "Tierra": {
        "Fuego": 2.0,
        "Eléctrico": 2.0,
        "Veneno": 2.0,
        "Roca": 2.0,
        "Acero": 2.0,
        "Planta": 0.5,
        "Bicho": 0.5,
        "Volador": 0.0,
    },
    "Volador": {
        "Planta": 2.0,
        "Lucha": 2.0,
        "Bicho": 2.0,
        "Eléctrico": 0.5,
        "Roca": 0.5,
        "Acero": 0.5,
    },
    "Psíquico": {
        "Lucha": 2.0,
        "Veneno": 2.0,
        "Psíquico": 0.5,
        "Acero": 0.5,
        "Siniestro": 0.0,
    },
    "Bicho": {
        "Planta": 2.0,
        "Psíquico": 2.0,
        "Siniestro": 2.0,
        "Fuego": 0.5,
        "Lucha": 0.5,
        "Veneno": 0.5,
        "Volador": 0.5,
        "Fantasma": 0.5,
        "Acero": 0.5,
        "Hada": 0.5,
    },
    "Roca": {
        "Fuego": 2.0,
        "Hielo": 2.0,
        "Volador": 2.0,
        "Bicho": 2.0,
        "Lucha": 0.5,
        "Tierra": 0.5,
        "Acero": 0.5,
    },
    "Fantasma": {
        "Psíquico": 2.0,
        "Fantasma": 2.0,
        "Siniestro": 0.5,
        "Normal": 0.0,
    },
    "Dragón": {
        "Dragón": 2.0,
        "Acero": 0.5,
        "Hada": 0.0,
    },
    "Siniestro": {
        "Psíquico": 2.0,
        "Fantasma": 2.0,
        "Lucha": 0.5,
        "Siniestro": 0.5,
        "Hada": 0.5,
    },
    "Acero": {
        "Hielo": 2.0,
        "Roca": 2.0,
        "Hada": 2.0,
        "Fuego": 0.5,
        "Agua": 0.5,
        "Eléctrico": 0.5,
        "Acero": 0.5,
    },
    "Hada": {
        "Lucha": 2.0,
        "Dragón": 2.0,
        "Siniestro": 2.0,
        "Fuego": 0.5,
        "Veneno": 0.5,
        "Acero": 0.5,
    },
}
