from typing import Dict

moves: Dict[str, Dict[str, int]] = {
    "Hoja Afilada": {"tipo": "Planta", "poder": 55},
    "Terremoto": {"tipo": "Tierra", "poder": 100},
    "Rayo Solar": {"tipo": "Planta", "poder": 120},
    "Garra Dragón": {"tipo": "Dragón", "poder": 80},
    "Lanzallamas": {"tipo": "Fuego", "poder": 90},
    "Llamarada": {"tipo": "Fuego", "poder": 110},
    "Hidrobomba": {"tipo": "Agua", "poder": 110},
    "Ice Beam": {"tipo": "Hielo", "poder": 90},
    "Hidroariete": {"tipo": "Agua", "poder": 120},
    "Impactrueno": {"tipo": "Eléctrico", "poder": 40},
    "Trueno": {"tipo": "Eléctrico", "poder": 110},
    "Voltio Cruel": {"tipo": "Eléctrico", "poder": 90},
    "Martillazo": {"tipo": "Normal", "poder": 80},
    "Megacuerno": {"tipo": "Bicho", "poder": 120},
    "Mega Puño": {"tipo": "Normal", "poder": 80},
    "Triataque": {"tipo": "Normal", "poder": 80},
    "Hiperrayo": {"tipo": "Normal", "poder": 150},
    "Giro Fuego": {"tipo": "Fuego", "poder": 100},
    "Colmillo Ígneo": {"tipo": "Fuego", "poder": 65},
    "Psíquico": {"tipo": "Psíquico", "poder": 90},
    "Confusión": {"tipo": "Psíquico", "poder": 50},
    "Psicorrayo": {"tipo": "Psíquico", "poder": 100},
    "Sumisión": {"tipo": "Lucha", "poder": 80},
    "Doble Patada": {"tipo": "Lucha", "poder": 60},
    "Lanzarrocas": {"tipo": "Roca", "poder": 50},
    "Explosión": {"tipo": "Normal", "poder": 250},
    "Bola Sombra": {"tipo": "Fantasma", "poder": 80},
    "Lengüetazo": {"tipo": "Fantasma", "poder": 30},
    "Pulso Umbrío": {"tipo": "Fantasma", "poder": 80},
    "Semilladora": {"tipo": "Planta", "poder": 80},
    "Patada Salto Alta": {"tipo": "Lucha", "poder": 85},
    "Mega Patada": {"tipo": "Lucha", "poder": 120},
    "Contra": {"tipo": "Lucha", "poder": 80},
    "Ultrapuño": {"tipo": "Lucha", "poder": 100},
    "Roca Afilada": {"tipo": "Roca", "poder": 100},
    "Enfado": {"tipo": "Dragón", "poder": 120},
    "Placaje": {"tipo": "Normal", "poder": 40},
    "Destructor": {"tipo": "Normal", "poder": 250},
    "Mordisco": {"tipo": "Siniestro", "poder": 80},
    "Ventisca": {"tipo": "Hielo", "poder": 110}
}